
## Mulitdimensional NumPy arrays lab
Enter your Python code after each prompt.

@author: Glenn Bruns


In [ ]:
import random
import numpy as np
import pandas as pd

In [ ]:
#read student exam score data as a 2D NumPy array
df = pd.read_csv("https://raw.githubusercontent.com/grbruns/cst383/master/sample-grades.csv").values

In [ ]:
#print the score for the first student (row 0) and the third problem (column 2)
print(df[0,2])

0


In [ ]:
#print all scores for student 15 (meaning row 15)
print(df[15])

[3 2 0 3 0 3 1 0 3 0 0 3 3 3 3 0 3 3 3 3 3 3 3 3 1 3 3 3 1 0 0 0 0]


In [ ]:
#print all scores for problems 0-3
print(df[::,0:4])

[[3 1 0 3]
 [3 2 0 3]
 [3 2 3 3]
 [3 2 0 3]
 [0 2 3 3]
 [0 1 3 3]
 [0 2 3 3]
 [3 3 3 3]
 [3 1 3 3]
 [0 2 3 3]
 [0 3 3 3]
 [3 2 3 3]
 [3 2 3 3]
 [3 3 3 3]
 [3 1 3 3]
 [3 2 0 3]
 [3 2 3 3]
 [3 3 3 3]
 [3 2 0 3]
 [0 3 3 3]
 [0 0 3 3]
 [3 2 3 3]
 [3 2 0 3]
 [0 1 3 3]
 [0 0 3 3]
 [3 1 3 3]
 [3 2 3 3]
 [0 2 3 3]
 [0 3 3 3]
 [0 2 0 3]
 [0 1 0 3]
 [3 2 0 3]
 [0 1 0 3]
 [3 2 3 3]
 [3 2 3 3]
 [3 2 3 3]
 [3 2 3 0]
 [3 3 3 3]
 [0 2 3 3]
 [0 2 3 3]
 [3 3 3 3]
 [3 2 0 3]
 [3 2 3 3]
 [3 2 3 3]
 [0 2 3 3]
 [3 2 3 3]
 [3 3 3 3]
 [3 2 3 3]
 [3 3 0 3]
 [3 0 0 3]]


In [ ]:
# print all scores for problems 1, 5, 7
print(df[::,[1, 5, 7]])

[[1 3 0]
 [2 3 3]
 [2 3 3]
 [2 3 3]
 [2 3 3]
 [1 3 3]
 [2 3 3]
 [3 3 3]
 [1 3 0]
 [2 3 0]
 [3 3 3]
 [2 3 3]
 [2 3 3]
 [3 3 3]
 [1 3 3]
 [2 3 0]
 [2 3 3]
 [3 3 3]
 [2 3 3]
 [3 3 0]
 [0 3 3]
 [2 0 3]
 [2 3 3]
 [1 3 3]
 [0 3 0]
 [1 3 0]
 [2 3 3]
 [2 3 3]
 [3 3 3]
 [2 3 3]
 [1 3 0]
 [2 3 3]
 [1 3 3]
 [2 3 3]
 [2 3 3]
 [2 3 3]
 [2 3 3]
 [3 3 3]
 [2 3 0]
 [2 3 3]
 [3 3 3]
 [2 3 3]
 [2 3 0]
 [2 3 0]
 [2 3 3]
 [2 3 0]
 [3 3 0]
 [2 3 3]
 [3 3 3]
 [0 0 3]]


In [ ]:
#assign the number of students to variable 'num_students'
num_students = df.shape[0]

In [ ]:
#run the following command to get random data representing scores
#on two additional extra credit problems

ec = np.random.choice(np.array([0,1,2,3], dtype='int64'), size=num_students*2).reshape(num_students, 2)

In [ ]:
#print the shape of ec
print(ec.shape)

(50, 2)


In [ ]:
#update df so that the two rightmost columns are the data in array ec
df[:,31:33] = ec

In [ ]:
#print the mean value of all the scores
print(np.mean(df))

2.0503030303030303


In [ ]:
# print the number of scores > 2 (np.sum applied to a boolean mask will
# give the number of True values in the mask))
print(np.sum(df > 2))

994


In [ ]:
# using a list comprehension, compute the total score for each student
# and assign the result to variable 'totals' as a NumPy array
totals = np.array([np.sum(scores) for scores in df])

In [ ]:
#print the dtype of totals; it should be int64
print(totals.dtype)

int64


In [ ]:
#assign the number of columns to variable 'num_problems'
num_problems = df.shape[1]

In [ ]:
# using a list comprehension, compute the average score for each 
# problem and assign the result to variable 'prob_means' as a NumPy array
prob_means = np.array([sum(problem) / len(df) for problem in zip(*df)])

In [ ]:
# what is the lowest of the average score values?
print(np.min(prob_means))

0.68


In [ ]:
# Is it legal to subtract an array with shape (35, ) from an 
# array with shape (50, 35)?  If so, what will happen? Write
# your answer as a comment.

# The array (35, ) will become (1, 35), and will be subtracted
# each row of the (50, 35) array


In [ ]:
# compute a new array df_centered, which is a 2D array with
# the same shape as df , but contains, for each column, the 
# column values minus the average value for each column.
df_centered = df - prob_means

In [ ]:
# What do you expect as the average values of the columns of
# dat_centered? Print the result to find out. 
print(np.array([df_centered.mean(axis=1)]))

[[ 0.16181818 -0.08060606  0.64666667 -0.14121212 -0.7169697  -0.65636364
  -0.20181818  0.34363636  0.52545455 -0.77757576 -0.44424242 -0.05030303
   0.22242424  0.46484848  0.16181818 -0.11090909  0.73757576  0.40424242
   0.19212121  0.52545455 -0.17151515  0.34363636 -0.23212121 -0.05030303
  -0.59575758  0.49515152  0.31333333  0.04060606  0.55575758 -0.50484848
  -0.17151515  0.25272727 -0.20181818  0.10121212  0.34363636  0.61636364
  -0.35333333  0.34363636 -0.17151515  0.22242424  0.16181818 -0.17151515
  -0.38363636 -0.41393939 -0.56545455 -0.17151515 -0.11090909  0.10121212
  -0.05030303 -0.77757576]]


In [ ]:
# consider extending idea about length of student trips, but make a matrix, 
# where each row is a student, and 'mpg', 'miles; are columns. In a separate
# array, show prices of gas as several gas stations.