# NumPy arrays lab

Enter your code below each comment



In [ ]:
import random
import numpy as np

Here is a list of the mileage (given in MPG) of students in my last class: 21.1, 26.6, 16.3, 33.7, 31.2, 52.0, 27.1

Create a NumPy array named 'mpg' from these values (use the given order).

In [ ]:
mpg = np.array([21.1, 26.6, 16.3, 33.7, 31.2, 52.0, 27.1])

Create a new array x that has the same length as mpg but every value is 25.0  (use the NumPy size property of mpg).

In [ ]:
x = np.full(mpg.size, 25.0)

print the mileage of the third student

In [ ]:
print(mpg[2])

16.3


print the mileage of the last student

In [ ]:
print(mpg[-1])

27.1


print the mileage of the first to the third students

In [ ]:
print(mpg[[0,2]])

[21.1 16.3]


print the mileage of every other student, starting with the first

In [ ]:
print(mpg[::2])

[21.1 16.3 31.2 27.1]


 Can you print the same mileages, but in reverse order?

In [ ]:
print(mpg[::-2])

[27.1 31.2 16.3 21.1]


 make a copy of mpg, named mpg2

In [ ]:
mpg2 = mpg.copy()

print the concatenation of mpg and mpg2


In [ ]:
print(np.concatenate([mpg, mpg2]))

[21.1 26.6 16.3 33.7 31.2 52.  27.1 21.1 26.6 16.3 33.7 31.2 52.  27.1]


print the data type (dtype) of mpg

In [ ]:
print(mpg.dtype)

float64


add 5.0 to every element of mpg2

In [ ]:
mpg2 = 5 + mpg2

Create a NumPy array 'miles' giving the distances each student has to travel to CSUMB.  The values are:

8.1, 5.4, 12.8, 42.1, 15.0, 22.2, 18.5

In [ ]:
miles = np.array([8.1, 5.4, 12.8, 42.1, 15.0, 22.2, 18.5])

The gallons used by a student in a round trip to CSUMB is the round-trip distance divided by miles-per-gallon.  Using vectorized operations, compute the number of gallons used by each student in a round trip to CSUMB.  Assign the result to variable 'gallons'.


In [ ]:
gallons = mpg/miles

 Create a boolean array that is True for every element of gallons that is less than 1.  Assign it to variable 'low_gas'.

In [ ]:
low_gas = gallons < 1

Use a boolean mask to get the values in gallons that are less than 1

Run the following line of code, which creates an array of a million random numbers between 0 and 1.

In [ ]:
x = np.full(1000000, random.random())

 write a python loop to compute the sum of the values in x

In [ ]:
sum = 0
for num in x:
  sum += num

Define a Python function named 'array_sum' that will return the sum of the specified NumPy array x.


In [ ]:
def array_sum(arr):
  sum = 0
  for num in arr:
    sum += num

Measure how long it takes for your function to sum the elements of the big array x you defined earlier.

hint: use %timeit

In [ ]:
%timeit array_sum(x)

126 ms ± 23.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


now measure how long it takes to do the same thing using np.sum

In [ ]:
%timeit np.sum(x)

360 µs ± 17.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


write code to show that slicing does not copy the input data

In [ ]:
print(mpg2)
mpg_slice = mpg2[1::2]
print(mpg_slice)
mpg_slice[-1] = 999
print(mpg2)

[26.1 31.6 21.3 38.7 36.2 57.  32.1]
[31.6 38.7 57. ]
[ 26.1  31.6  21.3  38.7  36.2 999.   32.1]


If you still have time, learn about some of the "magic commands" available in IPython.

https://ipython.org/ipython-doc/3/interactive/magics.html